apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb1
spec:
  selector:
    matchLabels:
      app: myweb1
  replicas: 1
  template:
    metadata:
      labels:
        app: myweb1
    spec:
      containers:
        - name: myweb1
          image: jeilbitna/cicdtest:blue
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myweb1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myweb1
root@master:~/0220_backup# ls
ansible.yaml  deployment.yaml  Dockerfile  index.html
root@master:~/0220_backup# cat ansible.yaml
---
- name: ansible deploy
  hosts: master
  gather_facts: false
  become: true

  tasks:
    - name: Git clone
      git:
        repo: https://github.com/jeilbitna/cicdtest.git
        dest: /root/cicdtest
        version: main
        clone: yes
        update: yes
        force: yes
      notify:
        - deploy

  handlers:
    - name: Deployment by kubectl apply
      shell: kubectl apply -f /root/cicdtest/deployment.yaml
