---
- name: Ansible deploy
  hosts: master
  gather_facts: false
  become: true

  tasks:
    - name: Git clone
      git:
        repo: https://github.com/jeilbitna/cicdtest.git
        dest: /root/cicdtest
        version: main
        clone: yes
        update: yes
        force: yes
      notify:
        - deploy

  handlers:
    - name: deploy
      shell: kubectl apply -f /root/cicdtest/deployment.yaml
