apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb1
spec:
  selector:
    matchLabels:
      app: myweb1
  replicas: 1
  template:
    metadata:
      labels:
        app: myweb1
    spec:
      containers:
        - name: myweb1
          image: jeilbitna/cicdtest:blue
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myweb1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myweb1
